### ISSUE TITLE
Wave Race 64 Combines Intro and Body

### ISSUE THREAD

**Issue by L-Spiro** [jombo23/N64-Tools#22]
Here is an example of how the intro section overlaps the looping section.

**Comment by SubDrag** [comment]
Probably not going to be fixable due to seq64 format, but this needs significantly more detail to even consider looking into it.  What song, what notes, what specifically is wrong in terms of midi, etc.

**Comment by L-Spiro** [comment]
My attachment did not upload.  Trying again.
[Wave Race 64 (U) (V1.1) 00000008 007AE8B0.zip](https://github.com/jombo23/N64-Tools/files/5932314/Wave.Race.64.U.V1.1.00000008.007AE8B0.zip)
This is only one example.  At least several of the stage songs have this issue.
From measures 1.1.1.0 to 5.1.1.0 the intro overlaps the looping section.

**Comment by SubDrag** [comment]
I don't think there's much I can do here.  Unfortunately it's a result of it being a microcode (and not really midi).  So it has jumps, things like that.  The Seq64 format it just tries to dump as much music as possible.  I guess you can try Seq64, see if it does any better, but the midi tool just goes through jumps once and tries to get as much music as possible, since it's really a microcode, and not a standard music paradigm:
https://github.com/sauraen/seq64

-------------------Track Chn 0 Layer 0-------------------
TRK 000005A5 Time: 00000001 CMD:      FC Jump and Link Offset 09C9
TRK 000009C9 Time: 00000001 CMD:      C2 Coarse Tune 00 (0)
TRK 000009CB Time: 00000001 Note TVD: 22 Note 22 Length 30 (48) Velocity 7F (127) Duration 85 (133) [True Note Length 0018]
TRK 000009CF Time: 00000031 CMD:      C2 Coarse Tune 0C (12)
TRK 000009D1 Time: 00000031 Note VD:  BA Note 3A [Timestamp 0030] Velocity 7F (127) Duration 85 (133) [True Note Length 0018]
TRK 000009D4 Time: 00000061 Note VD:  96 Note 16 [Timestamp 0030] Velocity 7F (127) Duration 85 (133) [True Note Length 0018]
TRK 000009D7 Time: 00000091 Note VD:  BA Note 3A [Timestamp 0030] Velocity 7F (127) Duration 85 (133) [True Note Length 0018]
TRK 000009DA Time: 000000C1 CMD:      FF END
... Returning from Subroutine to 000005A8
TRK 000005A8 Time: 000000C1 CMD:      FC Jump and Link Offset 09DB
TRK 000009DB Time: 000000C1 CMD:      C2 Coarse Tune 00 (0)
TRK 000009DD Time: 000000C1 Note TVD: 22 Note 22 Length 30 (48) Velocity 7F (127) Duration 85 (133) [True Note Length 0018]
TRK 000009E1 Time: 000000F1 CMD:      C2 Coarse Tune 0C (12)
TRK 000009E3 Time: 000000F1 Note TVD: 3A Note 3A Length 48 (72) Velocity 7F (127) Duration AE (174) [True Note Length 0018]
TRK 000009E7 Time: 00000139 Note TVD: 16 Note 16 Length 18 (24) Velocity 7F (127) Duration 0B (11) [True Note Length 0017]
TRK 000009EB Time: 00000151 Note VD:  BA Note 3A [Timestamp 0018] Velocity 7F (127) Duration 0B (11) [True Note Length 0017]
TRK 000009EE Time: 00000169 Note TVD: 16 Note 16 Length 48 (72) Velocity 7F (127) Duration AE (174) [True Note Length 0018]
TRK 000009F2 Time: 000001B1 CMD:      FF END
... Returning from Subroutine to 000005AB
TRK 000005AB Time: 000001B1 CMD:      FC Jump and Link Offset 09F3
TRK 000009F3 Time: 000001B1 CMD:      C2 Coarse Tune 0C (12)
TRK 000009F5 Time: 000001B1 Note TVD: 3A Note 3A Length 30 (48) Velocity 7F (127) Duration 85 (133) [True Note Length 0018]
TRK 000009F9 Time: 000001E1 Note VD:  96 Note 16 [Timestamp 0030] Velocity 7F (127) Duration 85 (133) [True Note Length 0018]
TRK 000009FC Time: 00000211 Note VD:  BA Note 3A [Timestamp 0030] Velocity 7F (127) Duration 85 (133) [True Note Length 0018]
TRK 000009FF Time: 00000241 CMD:      FF END
... Returning from Subroutine to 000005AE
TRK 000005AE Time: 00000241 CMD:      FC Jump and Link Offset 09C9
TRK 000009C9 Time: 00000241 CMD:      C2 Coarse Tune 00 (0)
TRK 000009CB Time: 00000241 Note TVD: 22 Note 22 Length 30 (48) Velocity 7F (127) Duration 85 (133) [True Note Length 0018]
TRK 000009CF Time: 00000271 CMD:      C2 Coarse Tune 0C (12)
TRK 000009D1 Time: 00000271 Note VD:  BA Note 3A [Timestamp 0030] Velocity 7F (127) Duration 85 (133) [True Note Length 0018]
TRK 000009D4 Time: 000002A1 Note VD:  96 Note 16 [Timestamp 0030] Velocity 7F (127) Duration 85 (133) [True Note Length 0018]
TRK 000009D7 Time: 000002D1 Note VD:  BA Note 3A [Timestamp 0030] Velocity 7F (127) Duration 85 (133) [True Note Length 0018]
TRK 000009DA Time: 00000301 CMD:      FF END
... Returning from Subroutine to 000005B1
