### ISSUE TITLE
Software closes when a new ROM is loaded, or a song being converted into MIDI.

### ISSUE THREAD

**Issue by Gorilli09** [jombo23/N64-Tools#30]
When I load in a new ROM, or convert a song into MIDI, the software closes.

**Comment by MyYeeziesHaveTheSneezies** [comment]
Hey, I've been having the exact same problem. I worked out what I was doing wrong and it looks like you might have the same problem as me. I created a GitHub account because I felt morally responsible to tell you how I fixed it xD

Before you load a ROM, you have to click on the drop down menu above the "Load ROM" button and select the ROM you are about to load. Only after that will clicking "Load ROM" do something and not crash the program.

This could have been explained if some instructions were inside the download, but I didn't find any. There's instructions here http://sheesh.us/tutorials/part-3-extracting-midi-files-from-any-n64-rom/ but I missed them on my first reading so I wouldn't be suprised if someone else would miss them too.

Hopefully you had the same issue as me and this helps!

**Comment by SubDrag** [comment]
Yeah sorry it doesn't try and auto-identify the ROM. You have to pick the game first, then load ROM.

**Comment by MyYeeziesHaveTheSneezies** [comment]
Bro no need to apologise, your N64MidiTool is litterally the lynch pin of my whole music dissertation! I'm doing research into how Game music scholars can use the tools available online (your N64MidiTool) to use the sequence data for their analysis; currently they just transcribe everything by ear (which is not only time consuming but misses out on the technical detail of how the music was made). So thanks a bunch for being part of making such a cool tool!

> Yeah sorry it doesn't try and auto-identify the ROM. You have to pick the game first, then load ROM.
